### ISSUE TITLE
Python/Conda environment management

### ISSUE THREAD

**Issue by asmith26** [lionfish0/daskec2lite#3]
Hi there,

I like the look of this project, but I do not understand how to manage consistent Python/Conda environment setups across a cluster.

Please can you explain how to manage environments across your cluster (similar to http://yarn.dask.org/en/latest/environments.html)

Many thanks!

**Comment by lionfish0** [comment]
I'm afraid the default doesn't handle this - I know it's annoying

This issue might help? https://github.com/dask/distributed/issues/1200

**Comment by asmith26** [comment]
Hi @lionfish0, many thanks for getting back to me. That looks like a helpful issue that you linked, many thanks for you help!
